### PR TITLE
Update to ES2015+ and syntax changes

### PR DESCRIPTION
**Pull request by sauron65**
replace `var` with `let` and `const` and add semicolons and spaces

### CODE REVIEW

**Comment by sauron65** [comment]
choose squash and merge

**Comment by sauron65** [comment]
any reason why you're not merging this?
If you're worried about the file size being to big then I'll make a PR to split it into multiple files.

**Comment by thingMake** [comment]
I don't want to change the code.

**Comment by sauron65** [comment]
what do you mean?

**Comment by sauron65** [comment]
will this ever be merged?

**Comment by sauron65** [comment]
No response in 2 days. Closing.

**Pull request closed without merging**
